version: '3'
services:  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: banking
    ports:
      - "3303:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: banking
      MYSQL_USER: root
      MYSQL_PASSWORD: example

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
    driver: local